server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_CLIENT_HOST}:${EUREKA_CLIENT_PORT}/eureka/

spring:
  application:
    name: HISTORY-SERVICE
  data:
    mongodb:
      uri: mongodb://${DB_HOST}:${DB_PORT}/${DB_NAME}