#server:
#  port: 8081
#spring:
#  application:
#    name: AUTH-SERVICE
#  datasource:
#    url: jdbc:postgresql://database-auth:5432/auth-db
#    username: postgres
#    password: 1234
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: 033f662cdda792dd4afd
#            client-secret:
#          google:
#            client-id: 73739720220-qblvgnhnm505ovttjsp1eje7qf1ajr0n.apps.googleusercontent.com
#            client-secret:
#
#  kafka:
#    #    listener: PLAINTEXT://kafka:9092
#    #    producer:
#    #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#    #      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      auto-offset-reset: earliest
#  cloud:
#    function:
#      definition: avatarProcess
#    stream:
#      bindings:
#        avatarProcess-in-0:
#          destination: user-avatar-response
#          content-type: application/json
#      kafka:
#        binder:
#          brokers: kafka:9092
#
#    compatibility-verifier:
#      enabled: false
#
#  data:
#    redis:
#      host: redis
#      port: 6379
#      url: redis://redis:6379
#  cache:
#    type: redis
#
#  servlet:
#    multipart:
#      max-file-size: 3MB
#      max-request-size: 5MB
#
#eureka:
#  client:
#    registerWithEureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka/


EUREKA_CLIENT_HOST: eureka-server
EUREKA_CLIENT_PORT: 6379

DB_HOST: database-auth
DB_PORT: 5432
DB_NAME: auth-db
DDL_AUTO: update
DB_USERNAME: postgres
DB_PASSWORD: password

KAFKA_HOST: kafka
KAFKA_PORT: 9092

REDIS_HOST: redis
REDIS_PORT: 6379
REDIS_URL: redis://redis:6379