EUREKA_CLIENT_HOST: eureka-server
EUREKA_CLIENT_PORT: 8761

DB_HOST: database-auth
DB_PORT: 5432
DB_NAME: auth-db
DDL_AUTO: update
DB_USERNAME: postgres
DB_PASSWORD: password

KAFKA_HOST: kafka
KAFKA_PORT: 9092

REDIS_HOST: redis
REDIS_PORT: 6379
REDIS_URL: redis://redis:6379