EUREKA_CLIENT_HOST: localhost
EUREKA_CLIENT_PORT: 8761

DB_HOST: localhost
DB_PORT: 5432
DB_NAME: transaction_service
DDL_AUTO: update
DB_USERNAME: postgres
DB_PASSWORD: 1234

KAFKA_HOST: localhost
KAFKA_PORT: 9092
