server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_CLIENT_HOST}:${EUREKA_CLIENT_PORT}/eureka/

spring:
  application:
    name: TRANSACTION-SERVICE
  data:
    mongodb:
      uri: mongodb://${DB_HOST}:${DB_PORT}/${DB_NAME}

  kafka:
    consumer:
      auto-offset-reset: earliest
    cloud:
      function:
        definition: abc
      stream:
        bindings:
          abc-in-0:
            destination:
            content-type: application/json
        kafka:
          binder:
            brokers: ${KAFKA_HOST}:${KAFKA_PORT}

      compatibility-verifier:
        enabled: false