#server:
#  port: 8082
#spring:
#  application:
#    name: PRODUCT-SERVICE
#  datasource:
#    url: jdbc:postgresql://database-product:5432/product-db
#    username: postgres
#    password: password
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#  kafka:
#    consumer:
#      auto-offset-reset: earliest
#    cloud:
#      function:
#        definition: productImageProcess
#      stream:
#        bindings:
#          productImageProcess-in-0:
#            destination: product-image-response
#            content-type: application/json
#        kafka:
#          binder:
#            brokers: kafka:9092
#
#      compatibility-verifier:
#        enabled: false

EUREKA_CLIENT_HOST: eureka-server
EUREKA_CLIENT_PORT: 6379

DB_HOST: database-product
DB_PORT: 5432
DB_NAME: product-db
DDL_AUTO: update
DB_USERNAME: postgres
DB_PASSWORD: password

KAFKA_HOST: kafka
KAFKA_PORT: 9092
